# Generated by Django 5.2 on 2025-04-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('category', models.CharField(choices=[('SEED', 'Seed'), ('LIZARD', 'Lizard'), ('TURTLE', 'Turtle'), ('WATER', 'Water'), ('FIRE', 'Fire'), ('ELECTRIC', 'Electric'), ('ROCK', 'Rock'), ('POISON', 'Poison'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic')], max_length=10)),
                ('genre', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('types', models.CharField(choices=[('PLANT', 'Plant'), ('POISON', 'Poison'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('ELECTRIC', 'Electric'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('ICE', 'Ice'), ('DRAGON', 'Dragon'), ('DARK', 'Dark'), ('FAIRY', 'Fairy'), ('STEEL', 'Steel'), ('FIGHTING', 'Fighting'), ('NORMAL', 'Normal'), ('GROUND', 'Ground'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('DARK', 'Dark')], max_length=255)),
                ('weaknesses', models.CharField(choices=[('PLANT', 'Plant'), ('POISON', 'Poison'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('ELECTRIC', 'Electric'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('ICE', 'Ice'), ('DRAGON', 'Dragon'), ('DARK', 'Dark'), ('FAIRY', 'Fairy'), ('STEEL', 'Steel'), ('FIGHTING', 'Fighting'), ('NORMAL', 'Normal'), ('GROUND', 'Ground'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('DARK', 'Dark')], max_length=255)),
            ],
        ),
    ]
